import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { keepPreviousData, useQuery } from "@tanstack/react-query";
import { Search } from "lucide-react";

import { Badge, Input } from "@repo/ui";

import { adminApi, type AdminAiReport } from "@shared/api/adminApi";
import { apiErrorMessage } from "@shared/api/httpClient";
import { DataTable, type Column } from "@shared/components/DataTable";
import { PageHeader } from "@shared/components/PageHeader";
import { Pagination } from "@shared/components/Pagination";
import { PageError } from "@shared/components/States";
import { formatDateTime } from "@shared/utils/format";

const LIMIT = 25;

const columns: Column<AdminAiReport>[] = [
  {
    key: "headline",
    header: "Headline",
    render: (r) => <span className="line-clamp-1 max-w-96">{r.headline}</span>
  },
  {
    key: "pet",
    header: "Pet / owner",
    render: (r) =>
      r.pet ? (
        <div>
          <p className="font-medium">{r.pet.name}</p>
          <p className="text-xs text-muted-foreground">{r.pet.ownerEmail}</p>
        </div>
      ) : (
        <span className="text-muted-foreground">—</span>
      )
  },
  {
    key: "score",
    header: "Score",
    className: "text-right",
    render: (r) => <Badge variant="secondary">{r.awarenessScore}</Badge>
  },
  {
    key: "model",
    header: "Model",
    render: (r) => (
      <span className="text-xs text-muted-foreground">{r.model ?? "—"}</span>
    )
  },
  {
    key: "generated",
    header: "Generated",
    render: (r) => (
      <span className="text-muted-foreground">{formatDateTime(r.generatedAt)}</span>
    )
  }
];

export function AiReportsPage() {
  const navigate = useNavigate();
  const [page, setPage] = useState(1);
  const [search, setSearch] = useState("");

  const query = useQuery({
    queryKey: ["admin", "ai-reports", { page, search }],
    queryFn: () =>
      adminApi.listAiReports({
        page,
        limit: LIMIT,
        search: search || undefined
      }),
    placeholderData: keepPreviousData
  });

  if (query.isError) {
    return (
      <PageError
        message={apiErrorMessage(query.error)}
        onRetry={() => query.refetch()}
      />
    );
  }

  return (
    <div className="space-y-4">
      <PageHeader
        title="AI reports"
        description="Wellness reports generated by the AI engine. Open one to inspect the full content."
      />

      <div className="relative w-full max-w-xs">
        <Search className="absolute left-2.5 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" />
        <Input
          className="pl-8"
          placeholder="Search headline, pet or owner…"
          value={search}
          onChange={(e) => {
            setSearch(e.target.value);
            setPage(1);
          }}
        />
      </div>

      <DataTable
        columns={columns}
        rows={query.data?.items}
        rowKey={(r) => r.id}
        isLoading={query.isLoading}
        emptyMessage="No AI reports found"
        onRowClick={(r) => navigate(`/ai-reports/${r.id}`)}
      />

      {query.data ? (
        <Pagination
          page={page}
          limit={LIMIT}
          total={query.data.total}
          onPageChange={setPage}
        />
      ) : null}
    </div>
  );
}
